### ISSUE TITLE
Question about process using 100% CPU of one core

### ISSUE THREAD

**Issue by donnex** [cdown/psi-notify#22]
Really appreciate psi-notify, awesome project :)

I got one small problem/question, but it may be out of psi-notifys scope.

I sometime get one process or another stuck at 100% CPU. Right now it seems to be some problem with pipewire that uses 100% CPU of one core. My problem is that I got 4 cores / 8 threads so this does not really get picked up by psi-notify. Even with my current config:

`threshold cpu some avg10 1.00`

I guess the total load of my CPU/machine is not really affected enough even if this process is stuck at using 100% CPU of one core.

I'm not running with `log_pressures` enabled at the moment so I can't really tell what the pressure is reported as at when this happens. 

I could try to lower the CPU pressure even lower than 1.00 but that'll may result in a lot of false positives.

Any advice for picking this up or do I just have to try with lower settings and find the right threshold for reporting this?

**Comment by cdown** [comment]
We have an explanation of how we calculate pressures here: https://facebookmicrosites.github.io/psi/docs/overview

So if (let's say) your machine has four cores, and this single-threaded process takes up 100% of one of them, it can only produce at maximum 25% `cpu some`, because it's not accessing all of the resources on the system. In reality it's probably less, as long as it's making forward progress, since it's probably not always blocked on the CPU.

PSI's goal is to measure resource contention across the machine, either at a cgroup or a machine scope. In that respect, this only takes up some limited amount of machine resources, so PSI also only reports a limited amount of machine resources being contended upon.

The correct answer really depends on what your application is doing. One option is to put it in its own cgroup and look at PSI there, and report yourself as necessary. Another is to look at the specific application behaviour triggering this.

**Comment by donnex** [comment]
Yeah, that was my understanding of psi as well. Thanks for the information and clarification.

The correct solution is of course that pipewire fixes the issue, which it did in the latest release.

The task of finding/alerting for CPU intensive processes or processes stuck at using 100% of one core is clearly something other than psi-notifys goal. Maybe I'll try to throw something together myself for this.

Thanks again for your help!
