### ISSUE TITLE
[Request] Include process name in notification

### ISSUE THREAD

**Issue by NICHOLAS85** [cdown/psi-notify#24]
If it were possible, including the process name in the notification could be useful for quickly identifying what tripped the alert.

**Comment by cdown** [comment]
It's often not possible to pinpoint which application is causing any shortage of memory/CPU/IO, since we don't know (and can't write code for every possible case of) the cgroup layout of your system, and pressure can even be cgroup-internal. Certainly it can't be done at the process level, only the cgroup level. That's why systemd like oomd require a full policy and understanding of your system to operate.

We may be able to offer some naive hints based on pressure, but I'd be reluctant to implement that because even that is likely to be very complex, and often wrong.

**Comment by NICHOLAS85** [comment]
Ahh that makes sense. Thanks for the response.
